# Generated by Django 5.2.7 on 2025-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_investment', models.FloatField(default=0)),
                ('expected_rate', models.FloatField(default=0)),
                ('years', models.IntegerField(default=0)),
                ('total_investment', models.FloatField(default=0)),
                ('future_value', models.FloatField(default=0)),
                ('gain', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
